### ISSUE TITLE
Lollypop crash when updating music is ends

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#104]
With the last commits, of course:
$ lollypop
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 212, in on_scan_finished
    self.update_lists(scanner)
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 140, in update_lists
    self._update_list_one(updater)
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 323, in _update_list_one
    update)
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 397, in _setup_list_artists
    selection_list.update(items)
AttributeError: 'SelectionList' object has no attribute 'update'

**Comment by yoseforb** [comment]
Still crash:
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 212, in on_scan_finished
    self.update_lists(scanner)
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 140, in update_lists
    self._update_list_one(updater)
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 323, in _update_list_one
    update)
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 397, in _setup_list_artists
    selection_list.update_values(items)
  File "/usr/lib/python3.4/site-packages/lollypop/selectionlist.py", line 128, in update_values
    self._add(value)
AttributeError: 'SelectionList' object has no attribute '_add'
