### ISSUE TITLE
Bug when adding music

### ISSUE THREAD

**Issue by M5oul** [gnumdk/lollypop#1047]
### Env
- Lollypop version: 0.9.231
- Linux distribution: Fedora 25

### Bug
First of all, I migrated `$HOME` and my music to a new Fedora instance.
From a clean Lollypop, adding my music, things are stuck:
```bash
file:///home/moul/Musique/Rammstein%20-%20Discography%20%5BFLAC%5D/Albums/2009%20-%20Liebe%20Ist%20Fur%20Alle%20Da%20(2%20CD%20Ltd.%20Ed.)/Cover/Back.jpg not detected as a music file
Adding file: file:///home/moul/Musique/'Pistache%20Lunaire'EP/19421_%5BYou_re_a_Towel%5D_Mayonaise_%5BDomaine_Public%5D_%5Bwww.dogmazic.net%5D.mp3

CollectionScanner::add2db(): Read tags
CollectionScanner::add2db(): Restore stats
CollectionScanner::add2db(): Add artists You re a Towel
CollectionScanner::add2db(): Add album artists 
CollectionScanner::add2db(): Add album: Pistache Lunaire EP, []
CollectionScanner::__scan(add): NOT NULL constraint failed: albums.mtime file:///home/moul/Musique/'Pistache%20Lunaire'EP/19421_%5BYou_re_a_Towel%5D_Mayonaise_%5BDomaine_Public%5D_%5Bwww.dogmazic.net%5D.mp3
CollectionScanner::__scan(): 'IntegrityError' object has no attribute 'message'
```

I also encounter this bug:
```bash
CollectionScanner::add2db(): Read tags
CollectionScanner::add2db(): Restore stats
CollectionScanner::add2db(): Add artists Angry Days
CollectionScanner::add2db(): Add album artists Angry Days
CollectionScanner::add2db(): Add album: Scientifically Accurate: Skulls, [8]
CollectionScanner::__scan(add): NOT NULL constraint failed: albums.mtime file:///home/moul/Musique/Angry%20Days%20-%20Scientifically%20Accurate-%20Skulls/Angry%20Days%20-%20Scientifically%20Accurate-%20Skulls%20-%2004%20The%20Beginner.flac
CollectionScanner::__scan(): 'IntegrityError' object has no attribute 'message'
SpotifyCharts::__update_for_url(): https://spotifycharts.com/regional/de/weekly/latest/download
SpotifyCharts::__update_for_url(): ÷ (Deluxe) - ['Ed Sheeran'] - 7qiZfU4dY1lWllzX7mPBI3
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/site-packages/lollypop/charts.py", line 64, in __update
    provider.update()
  File "/usr/lib/python3.5/site-packages/lollypop/charts_spotify.py", line 50, in update
    self.__update()
  File "/usr/lib/python3.5/site-packages/lollypop/charts_spotify.py", line 70, in __update
    self.__update_for_url(self.__ALL % language)
  File "/usr/lib/python3.5/site-packages/lollypop/charts_spotify.py", line 99, in __update_for_url
    web.save_album_thread(album, DbPersistent.CHARTS, [Type.SPOTIFY])
  File "/usr/lib/python3.5/site-packages/lollypop/web.py", line 98, in save_album_thread
    album_artist, genre_ids)
  File "/usr/lib/python3.5/site-packages/lollypop/web.py", line 194, in __save_track
    0, True)
  File "/usr/lib/python3.5/site-packages/lollypop/tagreader.py", line 480, in add_album
    loved, popularity, rate)
  File "/usr/lib/python3.5/site-packages/lollypop/database_albums.py", line 52, in add
    uri, loved, popularity, rate, 0))
sqlite3.IntegrityError: NOT NULL constraint failed: albums.mtime
```

I finally `rm -rf ~/.local/share/lollypop` and everything works fine.

This is what I encounter. I give you this feedback.
You could do what you want with this feedback and close this ticket.

**Comment by gnumdk** [comment]
Tested, all is working fine. I think you had imported a wrong db version. Message show that your sqlite db is not 0.9.231 version.
