### ISSUE TITLE
Crash when setting a mix

### ISSUE THREAD

**Issue by rCarto** [gnumdk/lollypop#1057]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version: 0.9.232
• Gtk Version:
• Linux distribution: xubuntu 16.04

Salut Cédric !

When I try to get a random mix (or never played, or new tunes...) lollypop crashes with:

```python
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 797, in __on_list_two_selected
    self.__update_view_playlists(selected_ids)
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 669, in __update_view_playlists
    view = PlaylistsView(playlist_ids)
  File "/usr/lib/python3/dist-packages/lollypop/view_playlists.py", line 73, in __init__
    self.__set_duration()
  File "/usr/lib/python3/dist-packages/lollypop/view_playlists.py", line 198, in __set_duration
    duration += Lp().playlists.get_duration(playlist_id)
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
```

++

ps: j'ai laissé tombé lollypop pour le raspberry, mon écran est pas adapté.

**Comment by gnumdk** [comment]
Et merde, moi qui venait juste de faire une nouvelle release à midi, c'est reparti :-/

Topette Tim ;)
