### ISSUE TITLE
Playing a radio station crashes Lollypop

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#1080]
• Lollypop version: latest master
• Gtk Version: 3.24.2
• Linux distribution: Fedora 26

Lollypop crashes when clicking to play favorite radio station. It crashes with the following output:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/lollypop/mpris.py", line 392, in __on_current_changed
    self.__update_metadata()
  File "/usr/local/lib/python3.6/site-packages/lollypop/mpris.py", line 328, in __update_metadata
    track_id = randint(Gst.SECOND0, 90000000)
  File "/usr/lib64/python3.6/site-packages/gi/overrides/__init__.py", line 39, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib64/python3.6/site-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gst' object has no attribute 'SECOND0'
```

**Comment by kostich** [comment]
Still having issues. Now it crashes with:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/lollypop/mpris.py", line 392, in __on_current_changed
    self.__update_metadata()
  File "/usr/local/lib/python3.6/site-packages/lollypop/mpris.py", line 328, in __update_metadata
    track_id = randint(Gst.SECOND, 90000000)
  File "/usr/lib64/python3.6/random.py", line 220, in randint
    return self.randrange(a, b+1)
  File "/usr/lib64/python3.6/random.py", line 198, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (1000000000,90000001, -909999999)
```

**Comment by gnumdk** [comment]
Fixed
