### ISSUE TITLE
Lollypop crashes when try to play

### ISSUE THREAD

**Issue by ViniciusBRodrigues** [gnumdk/lollypop#1163]
### Environment
- Lollypop version: 0.9.205
- GNOME/GTK+ versions: 3.20.2
- GNU/Linux distribution: openSUSE Leap 42.3

### Bug/Feature

When I try to play some file:

```
viniciusbr@linux-9urx:~> lollypop 
Gtk-Message: Failed to load module "unity-gtk-module"
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 859, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.4/site-packages/lollypop/collectionscanner.py", line 150, in __scan
    mtimes = Lp().tracks.get_mtimes()
  File "/usr/lib/python3.4/site-packages/lollypop/database_tracks.py", line 306, in get_mtimes
    result = sql.execute("SELECT uri, mtime FROM tracks")
sqlite3.OperationalError: no such column: mtime

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/player_bin.py", line 499, in __on_bus_message_tag
    self.current_track.mtime != 0) and\
  File "/usr/lib/python3.4/site-packages/lollypop/objects.py", line 43, in __getattr__
    attr_value = getattr(self.db, "get_" + attr)(self.id)
  File "/usr/lib/python3.4/site-packages/lollypop/database_tracks.py", line 595, in get_mtime
    rowid=?", (track_id,))
sqlite3.OperationalError: no such column: mtime
```

**Comment by bil-elmoussaoui** [comment]
@gnumdk I think the best way to avoid those kinds of issues is to have a system of migrations. This way, if the application was downgraded you can downgrade/upgrade the database however you like.  I'm not aware of a nice python library that handles this without too many dependencies but implementing one shouldn't be too hard for some basic situations.

**Comment by ViniciusBRodrigues** [comment]
I upgraded to 0.9.240 and when I open Lollypop nothing appears (no artists, no musics).

```
viniciusbr@linux-9urx:~> lollypop
Gtk-Message: Failed to load module "unity-gtk-module"

(lollypop:19815): Gtk-WARNING **: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 911, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/site-packages/lollypop/loader.py", line 49, in run
    result = self._target()
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 610, in load
    items = Lp().albums.get_rated()
  File "/usr/lib/python3.4/site-packages/lollypop/database_albums.py", line 545, in get_rated
    result = sql.execute(request, filters)
sqlite3.OperationalError: no such column: rate

```

**Comment by gnumdk** [comment]
Go in dconf-editor: /org/gnome/Lollypop and put db-version to 20
