### ISSUE TITLE
Playing MIDI files crashes (due to being unable to read tags?).

### ISSUE THREAD

**Issue by MineyMe** [gnumdk/lollypop#117]
A backtrace of the crash:
```
Unhandled exception in thread started by <bound method CollectionScanner._add of <CollectionScanner object at 0x7fa0fd27c048 (lollypop+collectionscanner+CollectionScanner at 0x7fa115d18a20)>>
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/collectionscanner.py", line 162, in _add
    track_id = self._add2db(f, 0, infos, True, sql)
  File "/usr/lib/python3.4/site-packages/lollypop/collectionscanner.py", line 250, in _add2db
    title = self.get_title(tags, filepath)
  File "/usr/lib/python3.4/site-packages/lollypop/tagreader.py", line 62, in get_title
    (exist, title) = tags.get_string_index('title', 0)
AttributeError: 'NoneType' object has no attribute 'get_string_index'
Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1296, in _shutdown
    _main_thread._delete()
  File "/usr/lib/python3.4/threading.py", line 1019, in _delete
    del _active[get_ident()]
KeyError: 140329345091328
```
Note that this is a MIDI file that was played using 'Open with', not one that is currently in my database.

**Comment by gnumdk** [comment]
Should be fixed

**Comment by MineyMe** [comment]
Confirmed fixed, thanks.
