### ISSUE TITLE
[0.9.30/master] Crash occurs when nearing the end of the song

### ISSUE THREAD

**Issue by MineyMe** [gnumdk/lollypop#120]
When the player reaches about 2 or 3 seconds from the end of the track, a crash occurs.

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/player_bin.py", line 243, in _on_stream_about_to_finish
    self.next()
  File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 51, in next
    self._set_next()
  File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 227, in _set_next
    self.next_track = LinearPlayer.next(self, sql)
  File "/usr/lib/python3.4/site-packages/lollypop/player_linear.py", line 36, in next
    sql)
  File "/usr/lib/python3.4/site-packages/lollypop/database_albums.py", line 524, in get_tracks
    (album_id,))
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140341927401216 and this is thread id 140341135771392
Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1296, in _shutdown
    _main_thread._delete()
  File "/usr/lib/python3.4/threading.py", line 1019, in _delete
    del _active[get_ident()]
KeyError: 140341135771392
```

PS: Not as important, but I noticed some packagers packaging the stable version of Lollypop (e.g. 0.9.20 and now 0.9.30) are not updating their packages from 0.9.15, presumably because there are no prepackaged sources in the 'releases' section.

**Comment by gnumdk** [comment]
0.9.20 isn't release yet...
