### ISSUE TITLE
Crash at start (missing module named 'lollypop.list')

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#123]
It something from last commits:
$ lollypop
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.4/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 22, in <module>
    from lollypop.application import Application
  File "/usr/lib/python3.4/site-packages/lollypop/application.py", line 24, in <module>
    from lollypop.player import Player
  File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 17, in <module>
    from lollypop.player_shuffle import ShufflePlayer
  File "/usr/lib/python3.4/site-packages/lollypop/player_shuffle.py", line 19, in <module>
    from lollypop.list import LinkedList
ImportError: No module named 'lollypop.list'

**Comment by gnumdk** [comment]
Should be fixed ;)

**Comment by yoseforb** [comment]
Thanks for the quick fix!
