### ISSUE TITLE
[Flatpak] Opening Radios crashing the app

### ISSUE THREAD

**Issue by alex285** [gnumdk/lollypop#1237]
when clicking on Radios

Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/lollypop/container.py", line 794, in __on_list_one_selected
    self.__update_view_radios()
  File "/app/lib/python3.5/site-packages/lollypop/container.py", line 718, in __update_view_radios
    view = RadiosView()
  File "/app/lib/python3.5/site-packages/lollypop/view_radios.py", line 38, in __init__
    self.__radios_manager = Radios()
  File "/app/lib/python3.5/site-packages/lollypop/radios.py", line 61, in __init__
    None)
GLib.Error: g-io-error-quark: Error opening directory '/home/alex/.local/share/lollypop/radios': No such file or directory (1)

Ubuntu 16.10
Flatpak version 0.8.7
Runtime GTK 3.24
Lollypop version 0.9.244

**Comment by alex285** [comment]
i noticed that after run the system installed Lollypop it created the `~/local/share/lollypop/radios`, so the Flatpak stopped to crash

so it basically happens only of you run Flatpak Lollypop, if you hadn't run system Lollypop before

**Comment by gnumdk** [comment]
After checking, this code has been removed from Lollypop :)
