### ISSUE TITLE
SpotifySearch, TypeError: constructor returned NULL

### ISSUE THREAD

**Issue by samjaninf** [gnumdk/lollypop#1243]
### Environment
- Lollypop version: 0.9.244
- GNOME/GTK+ versions: 3.24.2
- GNU/Linux distribution: Fedora 26

### Bug/Feature
Clicking any of the links on the left sidebar results in the app crashing and getting this error message:

```
Sep 08 18:22:23 localhost.localdomain org.gnome.Lollypop.desktop[14068]: /usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
Sep 08 18:22:23 localhost.localdomain org.gnome.Lollypop.desktop[14068]:   g_type = info.get_g_type()
Sep 08 18:22:23 localhost.localdomain org.gnome.Lollypop.desktop[14068]: /usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
Sep 08 18:22:23 localhost.localdomain org.gnome.Lollypop.desktop[14068]:   g_type = info.get_g_type()
Sep 08 18:22:23 localhost.localdomain org.gnome.Lollypop.desktop[14068]: /usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
Sep 08 18:22:23 localhost.localdomain org.gnome.Lollypop.desktop[14068]:   g_type = info.get_g_type()
Sep 08 18:22:23 localhost.localdomain org.gnome.Lollypop.desktop[14068]: Traceback (most recent call last):
Sep 08 18:22:23 localhost.localdomain org.gnome.Lollypop.desktop[14068]:   File "/app/lib/python3.5/site-packages/lollypop/widgets_album.py", line 190, in _on_eventbox_realize
Sep 08 18:22:23 localhost.localdomain org.gnome.Lollypop.desktop[14068]:     window.set_cursor(Gdk.Cursor(Gdk.CursorType.HAND2))
Sep 08 18:22:23 localhost.localdomain org.gnome.Lollypop.desktop[14068]:   File "/usr/lib/python3.5/site-packages/gi/overrides/Gdk.py", line 334, in __new__
Sep 08 18:22:23 localhost.localdomain org.gnome.Lollypop.desktop[14068]:     return cls.new(*args, **kwds)
Sep 08 18:22:23 localhost.localdomain org.gnome.Lollypop.desktop[14068]: TypeError: constructor returned NULL
Sep 08 18:22:23 localhost.localdomain org.gnome.Lollypop.desktop[14068]: list index out of range
Sep 08 18:22:23 localhost.localdomain org.gnome.Lollypop.desktop[14068]: SpotifySearch::get_track 'album'
```

With the Spotify search turned off this error is in journald:
```
Sep 08 18:27:36 localhost.localdomain org.gnome.Lollypop.desktop[18852]: /usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
Sep 08 18:27:36 localhost.localdomain org.gnome.Lollypop.desktop[18852]:   g_type = info.get_g_type()
Sep 08 18:27:36 localhost.localdomain org.gnome.Lollypop.desktop[18852]: /usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
Sep 08 18:27:36 localhost.localdomain org.gnome.Lollypop.desktop[18852]:   g_type = info.get_g_type()
Sep 08 18:27:36 localhost.localdomain org.gnome.Lollypop.desktop[18852]: /usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
Sep 08 18:27:36 localhost.localdomain org.gnome.Lollypop.desktop[18852]:   g_type = info.get_g_type()
Sep 08 18:27:36 localhost.localdomain org.gnome.Lollypop.desktop[18852]: Traceback (most recent call last):
Sep 08 18:27:36 localhost.localdomain org.gnome.Lollypop.desktop[18852]:   File "/app/lib/python3.5/site-packages/lollypop/widgets_album.py", line 190, in _on_eventbox_realize
Sep 08 18:27:36 localhost.localdomain org.gnome.Lollypop.desktop[18852]:     window.set_cursor(Gdk.Cursor(Gdk.CursorType.HAND2))
Sep 08 18:27:36 localhost.localdomain org.gnome.Lollypop.desktop[18852]:   File "/usr/lib/python3.5/site-packages/gi/overrides/Gdk.py", line 334, in __new__
Sep 08 18:27:36 localhost.localdomain org.gnome.Lollypop.desktop[18852]:     return cls.new(*args, **kwds)
Sep 08 18:27:36 localhost.localdomain org.gnome.Lollypop.desktop[18852]: TypeError: constructor returned NULL
Sep 08 18:27:36 localhost.localdomain org.gnome.Lollypop.desktop[18852]: list index out of range
```

**Comment by gnumdk** [comment]
You are using a broken cursor theme. #1185
