### ISSUE TITLE
Lollypop crashes on startup

### ISSUE THREAD

**Issue by krakn** [gnumdk/lollypop#1245]
BUG MAY BE REJECTED IF MISSING:

### Environment
- Lollypop version: 0.9.244.r66 (current master)
- GNOME/GTK+ versions: 3.24.3 / 3.22.21
- GNU/Linux distribution: Archlinux

### Bug/Feature

I'm attempting to build it using the following PKGBUILD:

```
# Maintainer: Dan Beste <dan.ray.beste@gmail.com>
# Contributor: Frederic Bezies < fredbezies at gmail dot com>
# Contributor: Ian Brunelli (brunelli) <ian@brunelli.me>

pkgname=lollypop-git
_gitname=lollypop
pkgver=0.9.244.r66.g86c07fef
pkgrel=1
pkgdesc='Lollypop is a new GNOME music playing application.'
arch=('i686' 'x86_64')
license=('GPL3')
url='https://gnumdk.github.io/lollypop-web/'
depends=(
  'desktop-file-utils' 'gst-python' 'gtk3'
  'python-cairo' 'python-dbus' 'python-gobject'
  'totem-plparser' 'python-pylast'
  'gobject-introspection' 'gtk3' 'appstream-glib'
  'gstreamer' 'itstool'
)
makedepends=('meson' 'ninja')
optdepends=(
  'easytag: tag editing'
  'flatpak: Flatpak Portal'
  'gst-libav: FFmpeg plugin for GStreamer'
  'kid3-qt: Store covers in tags'
  'libsecret: Last.FM support'
  'python-wikipedia: Wikipedia support'
  'youtube-dl: YouTube playback'
)
source=("git://github.com/gnumdk/${_gitname}.git")
sha256sums=('SKIP')
conflicts=("${_gitname}")
provides=("${_gitname}")

pkgver() {
  cd "${_gitname}"

  git describe --tags --long \
    | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

build() {
  cd "${_gitname}"

  meson builddir --prefix=/usr
}

package() {
	cd "${_gitname}"

	DESTDIR="$pkgdir" ninja -C builddir install
}
```

It builds successfully, then:

```
 » lollypop
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 22, in <module>
    from lollypop.application import Application
  File "/usr/lib/python3.6/site-packages/lollypop/application.py", line 38, in <module>
    from lollypop.window import Window
  File "/usr/lib/python3.6/site-packages/lollypop/window.py", line 16, in <module>
    from lollypop.container import Container
  File "/usr/lib/python3.6/site-packages/lollypop/container.py", line 23, in <module>
    from lollypop.lio import Lio
ModuleNotFoundError: No module named 'lollypop.lio'
```

My apologies if I am missing any details.

**Comment by krakn** [comment]
That was a quick fix!

Thanks!
