### ISSUE TITLE
ValueError: Namespace Soup not available

### ISSUE THREAD

**Issue by lukeoftheaura** [gnumdk/lollypop#1268]
- Lollypop version: 0.9.303.1-1
- GNU/Linux distribution: Antergos (arch based)

### Bug/Feature
Lollypop won't start, when I run in a terminal and check the output, I get this:
```
Namespace Soup not available
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist information disabled
$ sudo pip3 install pylast
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 22, in <module>
    from lollypop.application import Application
  File "/usr/lib/python3.6/site-packages/lollypop/application.py", line 36, in <module>
    from lollypop.utils import is_gnome, is_unity
  File "/usr/lib/python3.6/site-packages/lollypop/utils.py", line 18, in <module>
    from lollypop.helper_task import TaskHelper
  File "/usr/lib/python3.6/site-packages/lollypop/helper_task.py", line 14, in <module>
    gi.require_version("Soup", "2.4")
  File "/usr/lib/python3.6/site-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Soup not available
```

I have `libsoup-gnome` installed, so that shouldn't be the problem.

**Comment by gnumdk** [comment]
The issue is on Antergos...  Works on Arch.... You are missing gobject introspection for libsoup, go to Antergos forum.
