### ISSUE TITLE
Not buildable in Debian Stable

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1273]
### Environment
- Lollypop version: Git
- GNOME/GTK+ versions: Gnome 3.22.2
- GNU/Linux distribution: Debian Stretch

### Bug
Debian Stable (Stretch / 9) ships `meson 0.37.1`, but meson.build specifies `meson >0.40`. Could you make it buildable there, too, since this is an important system? Or does this involve big changes?

I get the following error:
```
$ meson builddir --prefix=/usr
The Meson build system
Version: 0.37.1
Source dir: /home/fbruetting/lollypop
Build dir: /home/fbruetting/lollypop/builddir
Build type: native build

Meson encountered an error in file meson.build, line 1, column 0:
Not enough arguments to project(). Needs at least the project name and one language
```

**Comment by gnumdk** [comment]
Just use my package from my ppa.
For building master: pip3 install --update meson

**Comment by fbruetting** [comment]
Would you add your PPA source to the readme file, please?

**Comment by gnumdk** [comment]
This is not for users, just go to lollypop website ;)

**Comment by fbruetting** [comment]
Well, the ppa somehow doesn’t work with Stretch:

```
# add-apt-repository ppa:gnumdk/lollypop
^CTraceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 122, in <module>
    shortcut = shortcut_handler(line)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 841, in shortcut_handler
    ret = factory(shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 393, in shortcut_handler
    return PPAShortcutHandler(shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 356, in __init__
    info = get_ppa_info(self.shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 327, in get_ppa_info
    ret = get_ppa_info_from_lp(user, ppa)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 92, in get_ppa_info_from_lp
    return get_info_from_lp(lp_url)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 88, in get_info_from_lp
    return _get_https_content_py3(lp_url)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 102, in _get_https_content_py3
    lp_page = urllib.request.urlopen(request, cafile=LAUNCHPAD_PPA_CERT)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
```

**Comment by gnumdk** [comment]
No idea, report bug to Debian.

Just add it manually: sources.list + gpg key

**Comment by fbruetting** [comment]
There are just ubuntu images, if I substitute <ubuntu-version> by <stretch>, it doesn’t work…? Do you need to enable Debian there, maybe? Would also explain why the PPA didn’t work.

**Comment by gnumdk** [comment]
Put this in your sources.list:
deb http://ppa.launchpad.net/gnumdk/lollypop/ubuntu artful main

**Comment by fbruetting** [comment]
```
Ign:7 http://ppa.launchpad.net/gnumdk/lollypop/ubuntu artful InRelease         
Fehl:8 http://ppa.launchpad.net/gnumdk/lollypop/ubuntu artful Release
  Verbindung mit ppa.launchpad.net:http nicht möglich:
Paketlisten werden gelesen... Fertig
E: The repository 'http://ppa.launchpad.net/gnumdk/lollypop/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

According to [this](https://askubuntu.com/questions/866901/xenial-repository-does-not-have-a-release-file), you need to add a Debian repo, seems I can’t use an Ubuntu-specific one.

**Comment by gnumdk** [comment]
Can't see the word debian here: https://askubuntu.com/questions/866901/xenial-repository-does-not-have-a-release-file

**Comment by gnumdk** [comment]
https://serverfault.com/a/860031 ?

**Comment by gnumdk** [comment]
Here it works on Jessie, but I can't test with Stretch

**Comment by fbruetting** [comment]
Yes, no Debian, but if Ubuntu 14.04 and 16.04 aren’t compatible, I’d assume that Ubuntu & Debian aren’t either.

Will check that tomorrow.

**Comment by gnumdk** [comment]
ArchLinux is cool too for a good GNOME experience.
Or Ubuntu 17.10 with gnome-session installed.

**Comment by gnumdk** [comment]
Will test on my server if it works as soon I take time to do a distr-upgrade :-)

**Comment by fbruetting** [comment]
I read of Arch problem all the time from wogue ^_o.
I really thought Debian runs good, but I have a lot of complications actually. Must see if I’m able to install Fedora here at work – at home Fedora runs splendid.

I tried several things I looked up, but none of them worked, and I don’t even have this trusted.gpg file at all.
