### ISSUE TITLE
Starting Lollypop depends on mouse theme

### ISSUE THREAD

**Issue by fbruetting** [gnumdk/lollypop#1297]
### Environment
- Lollypop version:
```
$ flatpak run org.gnome.Lollypop --version
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Lollypop 0.9.304
```
- GNOME/GTK+ versions: 3.26 / 3.22.25
- GNU/Linux distribution: F27

### Bug/Feature
When using “Breeze_Snow”, I get the following output, the window pops up for a few μs, and is then closed. Using Adwaita mouse theme let’s Lollypop start successfully, in contrast.

```
$ flatpak run org.gnome.Lollypop 
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
xkbcommon: ERROR: Key "<LFSH>" added to modifier map for multiple modifiers; Using Lock, ignoring Shift
Gdk-Message: Unable to load hand2 from the cursor theme
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/lollypop/toolbar_info.py", line 96, in _on_eventbox_realize
    eventbox.get_window().set_cursor(Gdk.Cursor(Gdk.CursorType.HAND2))
  File "/usr/lib/python3.5/site-packages/gi/overrides/Gdk.py", line 336, in __new__
    return cls.new(*args, **kwds)
TypeError: constructor returned NULL
```

**Comment by gnumdk** [comment]
Already reported, broken mouse theme... Will not fix, it's in GDK API...
