### ISSUE TITLE
Lollypop no run

### ISSUE THREAD

**Issue by shinigamicorei7** [gnumdk/lollypop#147]
I have this problem

```
(lollypop:28689): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1397:31: Missing name of pseudo-class

(lollypop:28689): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1400:33: Missing name of pseudo-class

(lollypop:28689): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1405:33: Missing name of pseudo-class

(lollypop:28689): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1408:33: Missing name of pseudo-class

(lollypop:28689): Gtk-WARNING **: Theme parsing error: gtk-contained.css:1411:33: Missing name of pseudo-class

(lollypop:28689): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3068:61: Missing name of pseudo-class

(lollypop:28689): Gtk-WARNING **: Theme parsing error: gtk-contained.css:3176:81: Missing name of pseudo-class
cannot import name Secret, introspection typelib not found
Last.fm authentication disabled
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 2135, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/lollypop", line 22, in <module>
    from lollypop.application import Application
  File "/usr/local/lib/python3.4/site-packages/lollypop/application.py", line 33, in <module>
    from lollypop.window import Window
  File "/usr/local/lib/python3.4/site-packages/lollypop/window.py", line 16, in <module>
    from lollypop.container import Container
  File "/usr/local/lib/python3.4/site-packages/lollypop/container.py", line 24, in <module>
    from lollypop.view_radios import RadiosView
  File "/usr/local/lib/python3.4/site-packages/lollypop/view_radios.py", line 17, in <module>
    from lollypop.widgets_radio import RadioWidget
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_radio.py", line 18, in <module>
    from lollypop.pop_radio import RadioPopover
  File "/usr/local/lib/python3.4/site-packages/lollypop/pop_radio.py", line 25, in <module>
    from lollypop.art import Art
  File "/usr/local/lib/python3.4/site-packages/lollypop/art.py", line 16, in <module>
    from lollypop.art_album import AlbumArt
  File "/usr/local/lib/python3.4/site-packages/lollypop/art_album.py", line 20, in <module>
    from lollypop.tagreader import TagReader
  File "/usr/local/lib/python3.4/site-packages/lollypop/tagreader.py", line 14, in <module>
    from gi.repository import GLib, Gst, GstPbutils
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 53, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name GstPbutils, introspection typelib not found
```
Help me!

**Comment by gnumdk** [comment]
https://packages.debian.org/fr/jessie/gir1.2-gstreamer-1.0
