### ISSUE TITLE
Added python-wikipedia as depends

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#160]

**Comment by ianbrunelli** [comment]
I would suggest to add it as an optional dependency, alongside of `pylast`.

It looks like that was the plan, but something is missing in the code.

```
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/application.py", line 145, in do_startup
    Lp.window = Window(self)
  File "/usr/lib/python3.4/site-packages/lollypop/window.py", line 46, in __init__
    self._setup_content()
  File "/usr/lib/python3.4/site-packages/lollypop/window.py", line 190, in _setup_content
    self._toolbar = Toolbar(self.get_application())
  File "/usr/lib/python3.4/site-packages/lollypop/toolbar.py", line 33, in __init__
    self._toolbar_playback = ToolbarPlayback()
  File "/usr/lib/python3.4/site-packages/lollypop/toolbar_playback.py", line 41, in __init__
    if Lp.lastfm is not None or Lp.wikipedia is not None:
AttributeError: type object 'Lp' has no attribute 'wikipedia'
```
