### ISSUE TITLE
GLib.Options error

### ISSUE THREAD

**Issue by jjgalvez** [gnumdk/lollypop#169]
I just tried to compile and run lollypop. I received no compile errors, but when I  run lollypop from a terminal I get the error below.

Traceback (most recent call last):
  File "/usr/local/bin/lollypop", line 47, in <module>
    app = Application()
  File "/usr/local/lib/python3.4/site-packages/lollypop/application.py", line 73, in __init__
    self.add_main_option("debug", b'd', GLib.OptionFlags.NONE,
AttributeError: 'Application' object has no attribute 'add_main_option'

**Comment by gnumdk** [comment]
Gtk version?

**Comment by jjgalvez** [comment]
3.12
