### ISSUE TITLE
recent ARCH update broke installation

### ISSUE THREAD

**Issue by sevachka** [gnumdk/lollypop#174]
after I have upgraded to last version (in Arch) I get the following output in Terminal:

[sebastian@e7440 ~]$ lollypop

** (lollypop:1651): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia

(lollypop:1651): Gtk-WARNING **: Theme parsing error: gtk-dark.css:82:30: Failed to import: Fehler beim Öffnen der Datei: Datei oder Verzeichnis nicht gefunden
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 572, in _on_list_one_selected
    self._update_view_artists(selected_id, None)
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 429, in _update_view_artists
    view = ArtistView(artist_id, genre_id)
  File "/usr/lib/python3.4/site-packages/lollypop/view_albums.py", line 38, in __init__
    self._artist_name = Lp.artists.get_name(artist_id)
  File "/usr/lib/python3.4/site-packages/lollypop/database_artists.py", line 66, in get_name
    (artist_id,))
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139739978229504 and this is thread id 139739454412544
Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1296, in _shutdown
    _main_thread._delete()
  File "/usr/lib/python3.4/threading.py", line 1019, in _delete
    del _active[get_ident()]
KeyError: 139739454412544

-------------------------------

Re-installation didn´t help. Is there any dependency missing?

**Comment by hotoiledgoblinsack** [comment]
Thanks for the quick response, unfortunately the commit did not resolve the issue for me. I deleted my entire music database, then Lollypop starts and regenerates it. On next startup, I get the same error again:

```
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 604, in _on_list_two_selected
    self._update_view_artists(selected_id, genre_id)
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 429, in _update_view_artists
    view = ArtistView(artist_id, genre_id)
  File "/usr/lib/python3.4/site-packages/lollypop/view_albums.py", line 38, in __init__
    self._artist_name = Lp.artists.get_name(artist_id)
  File "/usr/lib/python3.4/site-packages/lollypop/database_artists.py", line 66, in get_name
    (artist_id,))
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140373406549760 and this is thread id 140372877502208
Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1296, in _shutdown
    _main_thread._delete()
  File "/usr/lib/python3.4/threading.py", line 1019, in _delete
    del _active[get_ident()]
KeyError: 140372877502208
```

**Comment by gnumdk** [comment]
@slosd Help wanted, since the list is threaded, we have this bug.

Can't reproduce on my computer, any idea?

**Comment by gnumdk** [comment]
Is it ok with last commit?

**Comment by hotoiledgoblinsack** [comment]
At first sight everything seems to be working again now. The "All artists" view now also loads all the artists pretty much instantly (before it was gradually adding them), which is very nice. Thanks for the quick fix.

**Comment by gnumdk** [comment]
Cool :)

**Comment by kostich** [comment]
I am experiencing the same problem on Fedora 22.

```
[marko@skynet ~] $ lollypop 
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 572, in _on_list_one_selected
    self._update_view_artists(selected_id, None)
  File "/usr/lib/python3.4/site-packages/lollypop/container.py", line 429, in _update_view_artists
    view = ArtistView(artist_id, genre_id)
  File "/usr/lib/python3.4/site-packages/lollypop/view_albums.py", line 38, in __init__
    self._artist_name = Lp.artists.get_name(artist_id)
  File "/usr/lib/python3.4/site-packages/lollypop/database_artists.py", line 66, in get_name
    (artist_id,))
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 139705065686784 and this is thread id 139704508069632
Exception ignored in: <module 'threading' from '/usr/lib64/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 1297, in _shutdown
    _main_thread._delete()
  File "/usr/lib64/python3.4/threading.py", line 1020, in _delete
    del _active[get_ident()]
KeyError: 139704508069632
```

**Comment by slosd** [comment]
The threading is a bit convoluted at the moment. All sorts of methods on gtk widgets are called from a new thread so the widgets are able to use Lp.db, Lp.artists, etc. and not block. Ideally threads are only used in `Container` (container.py) for accessing the database and every widget method is then called on the main thread with the data. This would resolve these kind of issues and make it much easier to debug. @gnumdk I'll make some changes on my fork so you can have a look at it.

**Comment by gnumdk** [comment]
People report me this one as fixed
