### ISSUE TITLE
AttributeError: 'gi.repository.Gtk' object has no attribute 'Popover'

### ISSUE THREAD

**Issue by pt321** [gnumdk/lollypop#176]
When trying to run it first timet on Ubuntu 14.04 LTS

Traceback (most recent call last):
  File "/usr/bin/lollypop", line 22, in <module>
    from lollypop.application import Application
  File "/usr/lib/python3/dist-packages/lollypop/application.py", line 44, in <module>
    from lollypop.window import Window
  File "/usr/lib/python3/dist-packages/lollypop/window.py", line 16, in <module>
    from lollypop.container import Container
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 20, in <module>
    from lollypop.selectionlist import SelectionList
  File "/usr/lib/python3/dist-packages/lollypop/selectionlist.py", line 20, in <module>
    class SelectionPopover(Gtk.Popover):
  File "/usr/lib/python3/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'Popover'

**Comment by gnumdk** [comment]
Not supported

**Comment by pt321** [comment]
why does your PPA have a package for it

https://launchpad.net/~gnumdk/+archive/ubuntu/lollypop?field.series_filter=trusty

**Comment by gnumdk** [comment]
For elementary OS.
