### ISSUE TITLE
playlist not working 

### ISSUE THREAD

**Issue by abhi94** [gnumdk/lollypop#184]
1. close unexpectedly while clicking on the playlist
2. the add to playlist option is seen disabled
3. clicking on 'add to playlist' from the search results make the program crash
4. I'm running lollypop 0.9.35 on ubuntu 15.04

**Comment by gnumdk** [comment]
Send me lollypop output

**Comment by abhi94** [comment]
@gnumdk: When I click on the playlist option, this happens
abhijith@abhijith-dell:~$ lollypop
LastFM::_populate_loved_tracks: Invalid user supplied
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 552, in _on_list_one_selected
    self._update_view_playlists(None)
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 460, in _update_view_playlists
    self._stack.get_allocated_width()/2)
  File "/usr/lib/python3/dist-packages/lollypop/view_playlists.py", line 157, in __init__
    is_album)
  File "/usr/lib/python3/dist-packages/lollypop/widgets_playlist.py", line 214, in __init__
    builder.add_from_resource('/org/gnome/Lollypop/'
GLib.Error: gtk-builder-error-quark: Invalid property: GtkScrolledWindow.overlay_scrolling on line 3 (11)

I have to say that Lollypop is the beautiful and functional audio player out there... I'm addicted to it in 2-3 days.. Well suited for gnome.
thank you for your replay.

**Comment by gnumdk** [comment]
My bad, i added a gtk3.16 option in glade ui :(

**Comment by gnumdk** [comment]
0.9.37 should fix your issues.

**Comment by abhi94** [comment]
It's working now !! 
Version 0.9.38. Thank you.
