### ISSUE TITLE
AttributeError: 'gi.repository.Gtk' object has no attribute 'Popover'

### ISSUE THREAD

**Issue by ShvonderSiN** [gnumdk/lollypop#215]
Hello, installed on Linux Mint, the player does not run in the terminal writes the following
$ lollypop
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 22, in <module>
    from lollypop.application import Application
  File "/usr/lib/python3/dist-packages/lollypop/application.py", line 44, in <module>
    from lollypop.window import Window
  File "/usr/lib/python3/dist-packages/lollypop/window.py", line 16, in <module>
    from lollypop.container import Container
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 20, in <module>
    from lollypop.selectionlist import SelectionList
  File "/usr/lib/python3/dist-packages/lollypop/selectionlist.py", line 22, in <module>
    class SelectionPopover(Gtk.Popover):
  File "/usr/lib/python3/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'Popov
Tried to run on Linux Mint Mate and Linux Mint 17.2 17.2 Cinnamon

**Comment by gnumdk** [comment]
Too old distribution

**Comment by ShvonderSiN** [comment]
Linux Mint 17.2 latset distribution

**Comment by bil-elmoussaoui** [comment]
Well this distro does not use GTK 3.14 or a newer version; the ubuntu 14.04 version of lollypop is built for elementary OS freya that has GTK 3.14
