### ISSUE TITLE
Crash out of nowhere

### ISSUE THREAD

**Issue by kelvan** [gnumdk/lollypop#262]
Using 97b3c8d

Playing while indexing and deleting/renaming/tagging some music.
Didn't touch the current playing file.

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/player_bin.py", line 296, in _on_bus_eos
    debug("Player::_on_bus_eos(): %s" % self.current_track.uri)
  File "/usr/lib/python3.4/site-packages/lollypop/objects.py", line 236, in uri
    return GLib.filename_to_uri(self.path)
GLib.Error: g_convert_error: The pathname '' is not an absolute path (5)

**Comment by kelvan** [comment]
More crashes:

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 244, in _on_stream_start
    self.set_prev()
  File "/usr/lib/python3.4/site-packages/lollypop/player.py", line 201, in set_prev
    self.prev_track = LinearPlayer.prev(self)
  File "/usr/lib/python3.4/site-packages/lollypop/player_linear.py", line 79, in prev
    pos = self._albums.index(album.id)
ValueError: 1726 is not in list

**Comment by kelvan** [comment]
And even more:

Clicking on "All artists" -> empty list entry

Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/view_albums.py", line 70, in populate
    self._add_albums(albums)
  File "/usr/lib/python3.4/site-packages/lollypop/view_albums.py", line 90, in _add_albums
    widget = AlbumDetailedWidget(albums.pop(0),
IndexError: pop from empty list

**Comment by gnumdk** [comment]
ValueError: 1726 is not in list

Does this happened after a db update?

**Comment by kelvan** [comment]
Well I have a huge Music library and cleaning up a lot, so it's very likely there was an update at this time.
