### ISSUE TITLE
Lollypop 0.9.50 craches when trying to click on a song to play

### ISSUE THREAD

**Issue by iraklisg** [gnumdk/lollypop#269]
I built the deb file from src ppa
lollypop version: 0.9.42
os: debian 8 64bit gnome

ERROR EXAMPLE 1
$ lollypop

No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/view_albums.py", line 120, in _on_label_realize
    self._album.artist_id != Type.COMPILATIONS:
AttributeError: 'ArtistView' object has no attribute '_album'

ERROR EXAMPLE 2
$ lollypop

No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
PlaylistsManager::get_tracks: 'Loved tracks'
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_album.py", line 444, in _add_tracks
    pos)
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_track.py", line 391, in add_track
    utils.is_loved(track_id))
  File "/usr/local/lib/python3.4/site-packages/lollypop/utils.py", line 138, in is_loved
    sql)
  File "/usr/local/lib/python3.4/site-packages/lollypop/playlists.py", line 305, in is_present
    playlist_paths = self.get_tracks(playlist_name)
  File "/usr/local/lib/python3.4/site-packages/lollypop/playlists.py", line 223, in get_tracks
    self._playlists[playlist_name].set_tracks(tracks)
KeyError: 'Loved tracks'

ERROR EXAMPLE 3 (as long as I launch the app and click a random artist name from the side pane)
$ lollypop 
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
Unhandled exception in thread started by <bound method AlbumDetailedWidget.populate of <AlbumDetailedWidget object at 0x7f64641158b8 (lollypop+widgets_album+AlbumDetailedWidget at 0x2fa4780)>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/widgets_album.py", line 324, in populate
    sql)
  File "/usr/lib/python3/dist-packages/lollypop/database_albums.py", line 564, in get_tracks_infos
    (album_id, genre_id, disc))
sqlite3.OperationalError: no such column: tracks.length
Exception ignored in: <module 'threading' from '/usr/lib/python3.4/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 1296, in _shutdown
    _main_thread._delete()
  File "/usr/lib/python3.4/threading.py", line 1019, in _delete
    del _active[get_ident()]
KeyError: 140068851533568

**Comment by gnumdk** [comment]
I think you run 0.9.50 and then go back to 0.9.42.

rm -f .local/share/lollypop/lollypop.db

**Comment by iraklisg** [comment]
Basically what I just did was to remove the previous installation and try a fresh one via git clone https://github.com/gnumdk/lollypop.git
I would like to kindly report that the app is running smoothly so far. 
I did not use the rm -f .local/share/lollypop/lollypop.db command though...
Thank your for your excellent work with lollypop
BR
iraklis

**Comment by gnumdk** [comment]
Thanks ;)

**Comment by corebots** [comment]
i'm unsure about if i'm having the same problem or not. i've tried to re-install 0.9.50 several times, removed the database and removed any lollypop generated files I could find, but after lunching lollypop and clicking on an an artist or album lollypop still always crashes. output from terminal:

bash-4.3$ lollypop 
ArtDownloader::_get_album_art_lastfm: Album not found
PlaylistsManager::get_tracks: 'Loved tracks'
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_album.py", line 415, in _add_tracks
    pos)
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_track.py", line 386, in add_track
    utils.is_loved(track_id))
  File "/usr/local/lib/python3.4/site-packages/lollypop/utils.py", line 138, in is_loved
    sql)
  File "/usr/local/lib/python3.4/site-packages/lollypop/playlists.py", line 315, in is_present
    playlist_paths = self.get_tracks(playlist_name)
  File "/usr/local/lib/python3.4/site-packages/lollypop/playlists.py", line 229, in get_tracks
    self._playlists[playlist_name].set_tracks(tracks)
KeyError: 'Loved tracks'

I'm on Fedora 23 and GNOME 3.18 if that matters. thank you for the great music app!

**Comment by gnumdk** [comment]
Fixed ;)

**Comment by corebots** [comment]
oh it works now!! thank you so much for the quick fix!! 

however, when I enable the 'autoupdate music library' option in preferences, lollypop crashes withe the message 'lollypop is requesting additional codec installation' or similar, opening the software app with the message 'unfortunately, the software you're requesting hasn't been found' or similar. the output from terminal: 

bash-4.3$ lollypop 
ArtDownloader::_get_album_art_lastfm: Album not found
ArtDownloader::_get_album_art_lastfm: Album not found
ArtDownloader::_get_album_art_lastfm: Album not found
** Message: PackageKit: xid = 0
** Message: PackageKit: desktop_id = lollypop.desktop
** Message: PackageKit: Codec nice name: text/html decoder
** Message: PackageKit: structure: gstreamer1(decoder-text/html)()(64bit)
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/toolbar.py", line 94, in _on_current_changed
    self._toolbar_infos.on_current_changed(player)
  File "/usr/local/lib/python3.4/site-packages/lollypop/toolbar_infos.py", line 78, in on_current_changed
    False)
  File "/usr/local/lib/python3.4/site-packages/lollypop/art_album.py", line 125, in get_cover_for_uri
    pixbuf = self.pixbuf_from_tags(GLib.filename_from_uri(uri)[0], size)
  File "/usr/local/lib/python3.4/site-packages/lollypop/art_album.py", line 257, in pixbuf_from_tags
    infos = self.get_infos(filepath)
  File "/usr/local/lib/python3.4/site-packages/lollypop/tagreader.py", line 50, in get_infos
    infos = self._tagreader.discover_uri(uri)
GLib.Error: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12)
bash-4.3$

I've tried installing  all available gstreamer plugins, but the issue remains. might be a problem with my fedora installation though...

**Comment by gnumdk** [comment]
Your need gst libav from rpmfusion

**Comment by corebots** [comment]
"package gstreamer1-libav-1.4.5-1.fc22.x86_64 is already installed" but I understand this might be due to Fedora 23, since it's still in beta and rpm fusion isn't available for 23. anyway, thanks for your support.
