### ISSUE TITLE
Request : add multimedia keys support.

### ISSUE THREAD

**Issue by dastious** [gnumdk/lollypop#271]
Lollypop doesn't seem to support the multimedia keys (play/pause next), please add.
Or I did something wrong ? (Other music application work).

**Comment by region51** [comment]
@dastious 

Control+s: Lollypop settings
Control+f: Search
Control+p: Party mode
Control+m or F11: Fullscreen
x: Play
c: Pause
v: Stop
n: Next track
p: Previous track

**Comment by gnumdk** [comment]
Lollypop already support multimedia keys on GNOME like Desktop.

**Comment by gnumdk** [comment]
org.gnome.SettingsDaemon is needed.

**Comment by mancvso** [comment]
Would you give me a hint to enable "org.gnome.SettingsDaemon"?

**Comment by gnumdk** [comment]
Install gnome settings daemon and run it.

**Comment by mancvso** [comment]
Does not work :(
```
 gnome-settings-daemon 

** (gnome-settings-daemon:3094): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-xPdVTWbPaT: Konekto rifuziĝas

** (gnome-settings-daemon:3094): WARNING **: You can only run one xsettings manager at a time; exiting

** (gnome-settings-daemon:3094): WARNING **: Unable to start gnome_xsettings manager: Could not initialize xsettings manager.

** (gnome-settings-daemon:3094): WARNING **: Unable to register client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(gnome-settings-daemon:3094): clipboard-plugin-WARNING **: Clipboard manager is already running.

** (process:3118): WARNING **: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files

(gnome-settings-daemon:3094): PackageKit-WARNING **: failed to set proxy: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: SetProxy is not a valid method of interface org.freedesktop.PackageKit


(gnome-settings-daemon:3094): updates-plugin-WARNING **: failed to set proxies: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: SetProxy is not a valid method of interface org.freedesktop.PackageKit


(gnome-settings-daemon:3094): updates-plugin-WARNING **: failed to get time: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: GetTimeSinceAction is not a valid method of interface org.freedesktop.PackageKit


(gnome-settings-daemon:3094): updates-plugin-WARNING **: failed to get time: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 654, in _message_cb
    (candidate_method, parent_method) = _method_lookup(self, method_name, interface_name)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 246, in _method_lookup
    raise UnknownMethodException('%s is not a valid method of interface %s' % (method_name, dbus_interface))
dbus.exceptions.UnknownMethodException: org.freedesktop.DBus.Error.UnknownMethod: Unknown method: GetTimeSinceAction is not a valid method of interface org.freedesktop.PackageKit
```

**Comment by gnumdk** [comment]
Use dbus from shell and your desktop configuration.
