### ISSUE TITLE
Missing dependency in deb ?

### ISSUE THREAD

**Issue by SnouF** [gnumdk/lollypop#293]
Lollypop don't start, in terminal I have:
<pre>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/toolbar.py", line 94, in _on_current_changed
    self._toolbar_infos.on_current_changed(player)
  File "/usr/lib/python3/dist-packages/lollypop/toolbar_infos.py", line 78, in on_current_changed
    False)
  File "/usr/lib/python3/dist-packages/lollypop/art_album.py", line 125, in get_cover_for_uri
    pixbuf = self.pixbuf_from_tags(GLib.filename_from_uri(uri)[0], size)
  File "/usr/lib/python3/dist-packages/lollypop/art_album.py", line 257, in pixbuf_from_tags
    infos = self.get_infos(filepath)
  File "/usr/lib/python3/dist-packages/lollypop/tagreader.py", line 50, in get_infos
    infos = self._tagreader.discover_uri(uri)
GLib.Error: gst-core-error-quark: Il manque un greffon dans votre installation de GStreamer. (12)
</pre>
OS : debian unstable
Version : 0.9.51-1ppa1ubuntu1

**Comment by gnumdk** [comment]
Seems to be same issue, gnome 3.18 broken.
Got same bug while playing with gnome unstable on archlinux
