### ISSUE TITLE
Lollypop crashes when clicking on an album cover

### ISSUE THREAD

**Issue by cristobaltapia** [gnumdk/lollypop#306]
I have just compiled the latest version from github and get this error when clicking on an album:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/widgets_album.py", line 435, in _add_tracks
    pos)
  File "/usr/lib/python3.5/site-packages/lollypop/widgets_track.py", line 388, in add_track
    utils.is_loved(track_id))
  File "/usr/lib/python3.5/site-packages/lollypop/utils.py", line 134, in is_loved
    track_id)
  File "/usr/lib/python3.5/site-packages/lollypop/playlists.py", line 308, in exists_track
    (track_id, playlist_id))
sqlite3.OperationalError: no such column: main.tracks.filepath
```

**Comment by gnumdk** [comment]
$ rm -f ~/.local/share/lollypop/playlists.db

Sorry, i do not handle schema upgrades for dev version ;)

**Comment by cristobaltapia** [comment]
Thanks!

**Comment by yoseforb** [comment]
Thanks!
