### ISSUE TITLE
When i click the album ,lollypop crash

### ISSUE THREAD

**Issue by 0xbug** [gnumdk/lollypop#318]
```
AL lib: (WW) alc_initconfig: Failed to initialize backend "pulse"
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_album.py", line 435, in _add_tracks
    pos)
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_track.py", line 388, in add_track
    utils.is_loved(track_id))
  File "/usr/local/lib/python3.4/site-packages/lollypop/utils.py", line 134, in is_loved
    track_id)
  File "/usr/local/lib/python3.4/site-packages/lollypop/playlists.py", line 311, in exists_track
    (track_id, playlist_id))
sqlite3.OperationalError: no such column: main.tracks.filepath
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
AL lib: (EE) alc_cleanup: 1 device not closed
```

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/310

**Comment by 0xbug** [comment]
Thanks :+1:
