### ISSUE TITLE
Crash when attempting to renam playlist

### ISSUE THREAD

**Issue by cristobaltapia** [gnumdk/lollypop#322]
When trying to rename a playlist Lollypop crashes with the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/widgets_playlist.py", line 413, in _on_playlist_edited
    Lp.playlists.rename(name, old_name)
  File "/usr/lib/python3.5/site-packages/lollypop/playlists.py", line 124, in rename
    playlist_id = self.get_id(old_name, sql)
TypeError: get_id() takes 2 positional arguments but 3 were given
```

**Comment by gnumdk** [comment]
master branch? stable branch? 0.9.52?
