### ISSUE TITLE
Crash when clicking on compilation album cover

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#332]
When I want to play a song from a compilation, I click on a album cover and Lollypop crashes. Option "Play albums on click" is on. Lollypop 0.9.60. Fedora 22.

```
[user@box ~] $ lollypop 
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/widgets_album.py", line 435, in _add_tracks
    pos)
  File "/usr/lib/python3.4/site-packages/lollypop/widgets_track.py", line 388, in add_track
    utils.is_loved(track_id))
  File "/usr/lib/python3.4/site-packages/lollypop/utils.py", line 134, in is_loved
    track_id)
  File "/usr/lib/python3.4/site-packages/lollypop/playlists.py", line 311, in exists_track
    (track_id, playlist_id))
sqlite3.OperationalError: no such column: main.tracks.filepath
```

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/318

**Comment by kostich** [comment]
I've followed your advice listed in [this comment](https://github.com/gnumdk/lollypop/issues/306#issuecomment-147127135) and it doesn't crash now. But I do not have development version. I use your stable version from your COPR.
