### ISSUE TITLE
lollypop dosent work [help]

### ISSUE THREAD

**Issue by mehdi-alouane** [gnumdk/lollypop#34]
after building it from source in ubuntu "elementary" , trying to excute it but it told me that "No module named 'mutagen' " 
and that's the output : 
Traceback (most recent call last):
  File "/usr/local/bin/lollypop", line 19, in <module>
    from lollypop.application import Application
  File "/usr/local/lib/python3.4/site-packages/lollypop/application.py", line 18, in <module>
    from lollypop.window import Window
  File "/usr/local/lib/python3.4/site-packages/lollypop/window.py", line 20, in <module>
    from lollypop.collectionscanner import CollectionScanner
  File "/usr/local/lib/python3.4/site-packages/lollypop/collectionscanner.py", line 20, in <module>
    import mutagen
ImportError: No module named 'mutagen'
![screenshot from 2015-02-28 13 02 48](https://cloud.githubusercontent.com/assets/4208162/6426255/1efd5c2e-bf4a-11e4-9564-ed64d774c094.png)

**Comment by gnumdk** [comment]
Please use ubuntu package at least to get dependencies...

**Comment by gnumdk** [comment]
gnuppa as website is quite broken until release ;)
