### ISSUE TITLE
sqlite3.OperationalError on Arch Linux

### ISSUE THREAD

**Issue by stefabat** [gnumdk/lollypop#342]
Lollypop does not start on Arch Linux. I tried also to compile from git, I get the same error.
Here is the output from the CLI
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/toolbar.py", line 94, in _on_current_changed
    self._toolbar_title.on_current_changed(player)
  File "/usr/lib/python3.5/site-packages/lollypop/toolbar_title.py", line 80, in on_current_changed
    self._progress.set_range(0.0, player.current_track.duration * 60)
  File "/usr/lib/python3.5/site-packages/lollypop/objects.py", line 62, in __getattr__
    attr_value = getattr(self.db, "get_" + attr)(self.id, sql)
  File "/usr/lib/python3.5/site-packages/lollypop/database_tracks.py", line 376, in get_duration
    WHERE rowid=?", (track_id,))
sqlite3.OperationalError: no such column: duration
```

System: Arch Linux 64 bit, Kernel 4.2.3-1-ARCH
Python 3.5
Gnome 3.18
sqlite3 version 3.9.1 

I guess the problem comes from a too update version of python and not all the dependencies are up to date.

**Comment by gnumdk** [comment]
Install 0.9.52 and then 0.9.61.

Or rm -f ~/.local/share/lollypop/lollypop.db
