### ISSUE TITLE
error with fullscren

### ISSUE THREAD

**Issue by luchofuentes** [gnumdk/lollypop#344]
Hi, i have this error when I want fullscrenn

*Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/toolbar_end.py", line 183, in _on_party_btn_toggled
    Lp.player.set_party(active)
  File "/usr/lib/python3.5/site-packages/lollypop/player.py", line 193, in set_party
    self.set_next()
  File "/usr/lib/python3.5/site-packages/lollypop/player.py", line 243, in set_next
    self.next_track = ShufflePlayer.next(self)
  File "/usr/lib/python3.5/site-packages/lollypop/player_shuffle.py", line 64, in next
    track_id = self._shuffle_next()
  File "/usr/lib/python3.5/site-packages/lollypop/player_shuffle.py", line 193, in _shuffle_next
    return self._shuffle_next()
  File "/usr/lib/python3.5/site-packages/lollypop/player_shuffle.py", line 193,  in _shuffle_next
    return self._shuffle_next()
  File "/usr/lib/python3.5/site-packages/lollypop/player_shuffle.py", line 193, in _shuffle_next
    return self._shuffle_next()
  File "/usr/lib/python3.5/site-packages/lollypop/player_shuffle.py", line 193, in _shuffle_next
    return self._shuffle_next()
  File "/usr/lib/python3.5/site-packages/lollypop/player_shuffle.py", line 188, in _shuffle_next
    track_id = self._get_random()
  File "/usr/lib/python3.5/site-packages/lollypop/player_shuffle.py", line 202, in _get_random
    key=lambda *args: random.random()):
RecursionError: maximum recursion depth exceeded while calling a Python object*

**Comment by gnumdk** [comment]
Empty database?
