### ISSUE TITLE
Lollypop crashes

### ISSUE THREAD

**Issue by yoseforb** [gnumdk/lollypop#350]
$ lollypop
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:176: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Lastfm::_connect(): Authentication Failed - You do not have permissions to access the service
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/widgets_album.py", line 430, in _add_tracks
    pos)
  File "/usr/lib/python3.5/site-packages/lollypop/widgets_track.py", line 388, in add_track
    utils.is_loved(track_id))
  File "/usr/lib/python3.5/site-packages/lollypop/utils.py", line 134, in is_loved
    track_id)
  File "/usr/lib/python3.5/site-packages/lollypop/playlists.py", line 320, in exists_track
    (track_id, playlist_id))
sqlite3.OperationalError: no such column: main.tracks.filepath

**Comment by gnumdk** [comment]
#306
