### ISSUE TITLE
Bug at start of Lollypop

### ISSUE THREAD

**Issue by Salamandar** [gnumdk/lollypop#368]
You know better than me what to do with this ;)

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/toolbar.py", line 93, in _on_current_changed
    self._toolbar_infos.on_current_changed(player)
  File "/usr/lib/python3.5/site-packages/lollypop/toolbar_infos.py", line 79, in on_current_changed
    ArtSize.SMALL*self.get_scale_factor())
  File "/usr/lib/python3.5/site-packages/lollypop/art_album.py", line 187, in get_album_artwork2
    pixbuf = self.pixbuf_from_tags(GLib.filename_from_uri(uri)[0], size)
  File "/usr/lib/python3.5/site-packages/lollypop/art_album.py", line 245, in pixbuf_from_tags
    infos = self.get_infos(filepath)
  File "/usr/lib/python3.5/site-packages/lollypop/tagreader.py", line 50, in get_infos
    infos = self._tagreader.discover_uri(uri)
GLib.Error: gst-core-error-quark: Il manque un greffon dans votre installation de GStreamer. (12)

I just updated the library, then quitted and tried to re-open Lollypop.

**Comment by Salamandar** [comment]
The crash happens during the library update at launch.

**Comment by gnumdk** [comment]
https://github.com/gnumdk/lollypop/issues/359
