### ISSUE TITLE
Database migration

### ISSUE THREAD

**Issue by eonpatapon** [gnumdk/lollypop#379]
Hi,

I updated my code to master and installed it but it seems my DB is outdated. I don't remember exactly how to recover from this situation.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/lollypop/widgets_album.py", line 430, in _add_tracks
    pos)
  File "/usr/local/lib/python3.5/site-packages/lollypop/widgets_track.py", line 387, in add_track
    utils.is_loved(track_id))
  File "/usr/local/lib/python3.5/site-packages/lollypop/utils.py", line 148, in is_loved
    track_id)
  File "/usr/local/lib/python3.5/site-packages/lollypop/playlists.py", line 324, in exists_track
    (track_id, playlist_id))
sqlite3.OperationalError: no such column: main.tracks.filepath
```

**Comment by gnumdk** [comment]
rm -f ~/.local/share/lollypop/lollypop.db

**Comment by eonpatapon** [comment]
So I rebuilded the DB but unfortunately the error is still there. I get
the traceback when lollypop wan't to display album's content.

**Comment by gnumdk** [comment]
My bad. #306
Sorry for db clean up...

**Comment by eonpatapon** [comment]
Thanks, I made a backup so it's all fine ;)
