### ISSUE TITLE
Crash when trying to play music

### ISSUE THREAD

**Issue by d7rk** [gnumdk/lollypop#395]
On manjaro, with: 
* gstreamer 1.6.1-1
* lollypop 0.9.75.1

As soon as I click on an album, the programme crashes. In terminal, I get the following:

__Code__
(lollypop:9700): GStreamer-CRITICAL **: gst_date_time_new: assertion 'year > 0 && year <= 9999' failed

(lollypop:9700): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed

(lollypop:9700): GStreamer-CRITICAL **: gst_date_time_new: assertion 'year > 0 && year <= 9999' failed

(lollypop:9700): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/view_albums.py", line 192, in _on_album_activated
    self._populate_context(self._context_album_id)
  File "/usr/lib/python3.5/site-packages/lollypop/view_albums.py", line 137, in _populate_context
    size_group)
  File "/usr/lib/python3.5/site-packages/lollypop/widgets_album_context.py", line 35, in __init__
    pop_allowed, size_group)
  File "/usr/lib/python3.5/site-packages/lollypop/widgets_album.py", line 245, in __init__
    duration = Lp().albums.get_duration(album_id, genre_id)
  File "/usr/lib/python3.5/site-packages/lollypop/database_albums.py", line 653, in get_duration
    WHERE album_id=?", (album_id,))
sqlite3.OperationalError: no such column: duration
__/Code__

Cheers,

**Comment by gnumdk** [comment]
You database is broken:
rm -f ~/.local/share/lollypop/lollypop.db

Why do you use such an old version?
