### ISSUE TITLE
Launches but nothing in window and does not import music

### ISSUE THREAD

**Issue by rushsteve1** [gnumdk/lollypop#396]
OS: Manjaro (latest)
lollypop launches and sends the notification that it is updating music but the window looks like this:
![screenshot_2015-12-15_15-48-26](https://cloud.githubusercontent.com/assets/5970439/11823677/4f5f3288-a343-11e5-894f-b0153688a2bb.png)
This persists indefinitely.
When run from the terminal i get this:
>Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 923, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/site-packages/lollypop/container.py", line 67, in run
    result = self._target()
  File "/usr/lib/python3.5/site-packages/lollypop/container.py", line 439, in load
    artists = Lp().artists.get(genre_id)
  File "/usr/lib/python3.5/site-packages/lollypop/database_artists.py", line 150, in get
    ORDER BY artists.sortname COLLATE NOCASE")
sqlite3.OperationalError: no such column: artists.sortname

>Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 923, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/site-packages/lollypop/container.py", line 67, in run
    result = self._target()
  File "/usr/lib/python3.5/site-packages/lollypop/container.py", line 439, in load
    artists = Lp().artists.get(genre_id)
  File "/usr/lib/python3.5/site-packages/lollypop/database_artists.py", line 150, in get
    ORDER BY artists.sortname COLLATE NOCASE")
sqlite3.OperationalError: no such column: artists.sortname

It had said that 'wikipedia' and 'pylast' weren't install but i manually installed those with pip.

**Comment by gnumdk** [comment]
gsettings set org.gnome.Lollypop db-version 2

**Comment by rushsteve1** [comment]
This fixes it. Thanks.
