### ISSUE TITLE
Gtk AttributeError on Ubuntu 14.04

### ISSUE THREAD

**Issue by mrfuxi** [gnumdk/lollypop#406]
I can't start Lollypop.

Version: 0.9.75-1, Ubuntu 14.04

```bash
$ lollypop 
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 25, in <module>
    from lollypop.application import Application
  File "/usr/lib/python3/dist-packages/lollypop/application.py", line 38, in <module>
    from lollypop.window import Window
  File "/usr/lib/python3/dist-packages/lollypop/window.py", line 15, in <module>
    from lollypop.container import Container
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 19, in <module>
    from lollypop.selectionlist import SelectionList
  File "/usr/lib/python3/dist-packages/lollypop/selectionlist.py", line 20, in <module>
    class SelectionPopover(Gtk.Popover):
  File "/usr/lib/python3/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.Gtk' object has no attribute 'Popover'
```

**Comment by gnumdk** [comment]
Ubuntu 14.04 is not supported.

**Comment by mrfuxi** [comment]
That is fair enough. Could you please update PPA to reflect that?

**Comment by gnumdk** [comment]
Elementaryos is supported.
