### ISSUE TITLE
Lollypop crashes under Ubuntu 14.04

### ISSUE THREAD

**Issue by blade1989** [gnumdk/lollypop#427]
Here is the terminal output

    lollypop 
    Traceback (most recent call last):
    File "/usr/bin/lollypop", line 25, in <module>
    from lollypop.application import Application
    File "/usr/lib/python3/dist-packages/lollypop/application.py", line 38, in <module>
    from lollypop.window import Window
    File "/usr/lib/python3/dist-packages/lollypop/window.py", line 15, in <module>
    from lollypop.container import Container
    File "/usr/lib/python3/dist-packages/lollypop/container.py", line 19, in <module>
    from lollypop.selectionlist import SelectionList
    File "/usr/lib/python3/dist-packages/lollypop/selectionlist.py", line 20, in <module>
    class SelectionPopover(Gtk.Popover):
    File "/usr/lib/python3/dist-packages/gi/module.py", line 320, in __getattr__
    return getattr(self._introspection_module, name)
    File "/usr/lib/python3/dist-packages/gi/module.py", line 139, in __getattr__
    self.__name__, name))
    AttributeError: 'gi.repository.Gtk' object has no attribute 'Popover'

**Comment by gnumdk** [comment]
Not compatible with Ubuntu 14.04 (Do not handle an essential widget)
