### ISSUE TITLE
Lollypop crahs when I try to listen radio station

### ISSUE THREAD

**Issue by ibneurona** [gnumdk/lollypop#494]
I'm running on EOS Freya, Lollypop version 0.9.85 and when I try to listen radio on the Lollypop player, it crash, that's what I get in terminal on the end lines:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/player_bin.py", line 449, in _on_bus_error
    if self._codecs.is_missing_codec(message):
  File "/usr/lib/python3/dist-packages/lollypop/codecs.py", line 63, in is_missing_codec
    if error.matches(Gst.CoreError.quark(),
AttributeError: 'GError' object has no attribute 'matches'

**Comment by gnumdk** [comment]
WONT FIX as Lollypop for EOS dev is closed.

But, you are just missing a codec for your stream.
