### ISSUE TITLE
Lollypop crashes after left click

### ISSUE THREAD

**Issue by pawelad** [gnumdk/lollypop#523]
After upgrading to `0.9.90` on elementary OS Freya, Lollypp crashes on left click.

Left click on album:
```
$ lollypop -d
Namespace WebKit2 not available for version 4.0
WebKit support disabled
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/view_albums.py", line 246, in _on_album_activated
    self._populate_context(self._context_album_id)
  File "/usr/lib/python3/dist-packages/lollypop/view_albums.py", line 173, in _populate_context
    size_group)
  File "/usr/lib/python3/dist-packages/lollypop/widgets_album_context.py", line 34, in __init__
    update_albums)
  File "/usr/lib/python3/dist-packages/lollypop/widgets_album.py", line 559, in __init__
    self._child_height = TrackRow.get_best_height(self)
  File "/usr/lib/python3/dist-packages/lollypop/widgets_track.py", line 422, in get_best_height
    image_spacing = Gtk.Button().style_get_property('image-spacing')
TypeError: style_get_property() takes exactly 3 arguments (2 given)
```

Left click on artist name:
```
$ lollypop -d
Namespace WebKit2 not available for version 4.0
WebKit support disabled

** (lollypop:2067): CRITICAL **: totem_pl_parser_parse_with_base_async: assertion 'strstr (uri, "://") != NULL' failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/view_artist_albums.py", line 56, in populate
    self._add_albums(albums)
  File "/usr/lib/python3/dist-packages/lollypop/view_artist_albums.py", line 119, in _add_albums
    self._artist_ids)
  File "/usr/lib/python3/dist-packages/lollypop/widgets_album.py", line 559, in __init__
    self._child_height = TrackRow.get_best_height(self)
  File "/usr/lib/python3/dist-packages/lollypop/widgets_track.py", line 422, in get_best_height
    image_spacing = Gtk.Button().style_get_property('image-spacing')
TypeError: style_get_property() takes exactly 3 arguments (2 given)
```

Clicking on overlay play icon works as expected.

**Comment by gnumdk** [comment]
0.9.91 released to fix this crash
