### ISSUE TITLE
Namespace WebKit2 not available

### ISSUE THREAD

**Issue by dlanileonardo** [gnumdk/lollypop#554]
-Lollypop version: 0.9.94
-Gtk Version: libgtk-3-0 (3.16.7)
-Linux distribution: Ubuntu 15.10

-Describe your bug here:

After update i got this:

``` 
$ lollypop
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 25, in <module>
    from lollypop.application import Application
  File "/usr/lib/python3/dist-packages/lollypop/application.py", line 40, in <module>
    from lollypop.window import Window
  File "/usr/lib/python3/dist-packages/lollypop/window.py", line 15, in <module>
    from lollypop.container import Container
  File "/usr/lib/python3/dist-packages/lollypop/container.py", line 22, in <module>
    from lollypop.view_artist import ArtistView
  File "/usr/lib/python3/dist-packages/lollypop/view_artist.py", line 18, in <module>
    from lollypop.pop_info import InfoPopover
  File "/usr/lib/python3/dist-packages/lollypop/pop_info.py", line 21, in <module>
    from lollypop.widgets_web import OpenLink
  File "/usr/lib/python3/dist-packages/lollypop/widgets_web.py", line 14, in <module>
    gi.require_version('WebKit2', '4.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 100, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace WebKit2 not available
```

**Comment by gnumdk** [comment]
See closed bugs

**Comment by gnumdk** [comment]
#552
