### ISSUE TITLE
Build in Chromecast support

### ISSUE THREAD

**Issue by KeizerDev** [gnumdk/lollypop#589]
Last day I created a plugin for Rhythmbox to support a Chromecast(https://github.com/KeizerDev/Rhythmbox-Chromecast). 

Now I was wondering if I could do the same for lollypop and make it more close to the base of the music player.  
I can see Chromecast support as a big advantage and I'm pretty sure a lot of people would be very happy with it!

If we use this library(https://github.com/balloob/pychromecast) it would be pretty easy to be build in, I think it can be there in like two or three days.

Let me know what your thoughts are about this!

KeizerDev

**Comment by gnumdk** [comment]
How does it works? Is it like DLNA?

**Comment by gnumdk** [comment]
Ok, DNLA from Google... So support for Chromecast is no.

Better option is support for all DLNA devices. But for me, DLNA is really poor for audio, I really prefer bluetooth/airplay:
- No gapless support
- No crossfading support

**Comment by gnumdk** [comment]
And not working here:
Traceback (most recent call last):
  File "/home/gnumdk/.local/share/rhythmbox/plugins/chromecast/ChromecastSource.py", line 166, in cell_data_func
    title = entry[0]
TypeError: 'RhythmDBEntry' object does not support indexing
192.168.0.24 - - [26/Apr/2016 10:20:23] "GET / HTTP/1.1" 200 103253
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 453, in _write
    self.stdout.write(data)
  File "/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Relais brisé (pipe)
192.168.0.24 - - [26/Apr/2016 10:20:23] "GET / HTTP/1.1" 500 59
Traceback (most recent call last):
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 279, in write
    self._write(data)
  File "/usr/lib/python3.5/wsgiref/handlers.py", line 453, in _write
    self.stdout.write(data)
  File "/usr/lib/python3.5/socket.py", line 593, in write
    return self._sock.send(b)
BrokenPipeError: [Errno 32] Relais brisé (pipe)

**Comment by gnumdk** [comment]
https://github.com/masmu/pulseaudio-dlna

Works with pulseaudio dlna and my Android FreeBox.
