### ISSUE TITLE
can't launch after crash

### ISSUE THREAD

**Issue by corebots** [gnumdk/lollypop#621]
Lollypop is about albums, designed for album playback.
Playlists are presents for later usage (phone sync, specific party, ...)
If you really need a player designed around playlists, Lollypop is a bad choice ;)

-Lollypop version: cloned now from git
-Gtk Version: gtk3-3.18.9-1.fc23.x86_64
-Linux distribution: fedora 23

-Describe your bug here:
Thanks for the latest updates, lollypop now seemed much more fluid when switching between views(coverart loading). however, I've run into an issue: tried to change size of cover thumbnails and it took long time for loading and then crashed. now when trying to launch i get this:

$ lollypop
Fontconfig error: "/etc/fonts/conf.d/66-google-noto-sans-brahmi.conf", line 1: no element found

(lollypop:3201): GdkPixbuf-CRITICAL **: gdk_pixbuf_new_from_file_at_scale: assertion 'width > 0 || width == -1' failed
constructor returned NULL

(lollypop:3201): GdkPixbuf-CRITICAL **: gdk_pixbuf_new: assertion 'width > 0' failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/art_album.py", line 143, in get_album_artwork
    size)
TypeError: constructor returned NULL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/site-packages/lollypop/view.py", line 169, in lazy_loading
    widget.populate()
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_album.py", line 430, in populate
    self.set_cover()
  File "/usr/local/lib/python3.4/site-packages/lollypop/widgets_album.py", line 64, in set_cover
    self._cover.get_scale_factor())
  File "/usr/local/lib/python3.4/site-packages/lollypop/art_album.py", line 187, in get_album_artwork
    return self.get_default_icon('folder-music-symbolic', size, scale)
  File "/usr/local/lib/python3.4/site-packages/lollypop/art_base.py", line 70, in get_default_icon
    size)
TypeError: constructor returned NULL

**Comment by gnumdk** [comment]
Can reproduce setting a stupid value with dconf... Do you play with dconf?
dconf read /org/gnome/Lollypop/cover-size

**Comment by corebots** [comment]
no I haven't touch dconf in a while.... as stated, I've only tried to change the size with the slider of lollypop preferences, I've just moved it a bit to the left, then the above described happened. but I've updated now and all is good! thank you for the quick fix :)

**Comment by gnumdk** [comment]
So there is an issue with slider... Really strange!
