### ISSUE TITLE
Lollypop crashes after a song finishes playing

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#700]
-Lollypop version: master 3228f59da73f016b6f52c1e754d1b1145683ee8b
-Gtk Version: 3.20.8
-Linux distribution: Fedora 24

Lollypop crashes after it completes playing the first song. Traceback:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/lollypop/controllers.py", line 230, in _update_position
    value = Lp().player.position/1000000
  File "/usr/local/lib/python3.5/site-packages/lollypop/player_bin.py", line 199, in position
    self._do_crossfade(duration)
  File "/usr/local/lib/python3.5/site-packages/lollypop/player_bin.py", line 305, in _do_crossfade
    self._track_finished(self.current_track, self._start_time)
AttributeError: 'Player' object has no attribute '_track_finished'
```

**Comment by gnumdk** [comment]
Thanks, cleaning all lollypop code, so may have some more ;)
