### ISSUE TITLE
Another crash

### ISSUE THREAD

**Issue by d9h02f** [gnumdk/lollypop#733]
Not sure how this happened:

```
Traceback (most recent call last):

  File "/usr/lib/python3.5/site-packages/lollypop/view_playlists.py", line 143, in _on_jump_button_clicked
    y = self.__playlists_widget.get_current_ordinate()

  File "/usr/lib/python3.5/site-packages/lollypop/widgets_playlist.py", line 108, in get_current_ordinate
    if child.get_id() == Lp().player.current_track.id:

AttributeError: 'PlaylistRow' object has no attribute 'get_id'
```

**Comment by region51** [comment]
lollypop-0.9.202 broken
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/widgets_track.py", line 235, in __on_button_press
    self.__popup_menu(widget, event.x, event.y)
  File "/usr/lib/python3.5/site-packages/lollypop/widgets_track.py", line 260, in __popup_menu
    popover = TrackMenuPopover(self._track, TrackMenu(self._track))
  File "/usr/lib/python3.5/site-packages/lollypop/pop_menu.py", line 605, in __init__
    grid.add(edit)
UnboundLocalError: local variable 'edit' referenced before assignment
```

**Comment by blackjackshellac** [comment]
This is from master (369fa21382a43bd40213f2a519af86cb82736293),

Player::restore_state(): track missing
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/lollypop/mpris.py", line 59, in on_method_call
    result = getattr(self, method_name)(*args)
  File "/usr/local/lib/python3.5/site-packages/lollypop/mpris.py", line 278, in GetAll
    ret[property_name] = self.Get(interface, property_name)
  File "/usr/local/lib/python3.5/site-packages/lollypop/mpris.py", line 246, in Get
    return GLib.Variant('x', Lp().player.position / 60)
  File "/usr/local/lib/python3.5/site-packages/lollypop/player_bin.py", line 196, in position
    if self._crossfading and self.current_track.duration > 0:
TypeError: unorderable types: NoneType() > int()

**Comment by blackjackshellac** [comment]
BTW, there also seems to be a parameter missing in a call to set_fraction in src/container.py,

```
diff --git a/src/container.py b/src/container.py
index 6d2d84e..6351fcd 100644
--- a/src/container.py
+++ b/src/container.py
@@ -287,7 +287,7 @@ class Container:
             self.__progress.pulse()
             return True
         else:
-            self.__progress.set_fraction(0.0)
+            self.__progress.set_fraction(0.0, self)
             return False
 
     def __setup_view(self):

```
