### ISSUE TITLE
Lollypop doesn't start

### ISSUE THREAD

**Issue by kostich** [gnumdk/lollypop#736]
-Lollypop version: master revision a15d445c72d91bd41b3f43e233328d1ddb7497be
-Gtk Version: 3.20.9
-Linux distribution: Fedora 24

-Describe your bug here:
Lollypop crashes on start with the following output:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/lollypop/mpris.py", line 59, in on_method_call
    result = getattr(self, method_name)(*args)
  File "/usr/local/lib/python3.5/site-packages/lollypop/mpris.py", line 278, in GetAll
    ret[property_name] = self.Get(interface, property_name)
  File "/usr/local/lib/python3.5/site-packages/lollypop/mpris.py", line 246, in Get
    return GLib.Variant('x', Lp().player.position / 60)
  File "/usr/local/lib/python3.5/site-packages/lollypop/player_bin.py", line 196, in position
    if self._crossfading and self.current_track.duration > 0:
TypeError: unorderable types: NoneType() > int()
```

**Comment by gnumdk** [comment]
Send me your db by email

**Comment by gnumdk** [comment]
Please test with current git.

**Comment by kostich** [comment]
Seems to be working now. Do you still require my .dbs?

**Comment by gnumdk** [comment]
No ;)
