### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by M5oul** [gnumdk/lollypop#751]
- Lollypop version: 0.9.203/Copr
- Gtk Version: 3.20
- Linux distribution: Fedora 24

- Describe your bug here:

```fish
open monnaie_libre_68.ogg 
moul@moulinette ~/Téléchargements> No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
/usr/lib64/python3.5/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib64/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib64/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
moul@moulinette ~/Téléchargements> 
moul@moulinette ~/Téléchargements> open monnaie_libre_68.ogg 
moul@moulinette ~/Téléchargements> No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia
/usr/lib64/python3.5/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib64/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib64/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 385, in __on_current_changed
    self.__update_metadata()
  File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 343, in __update_metadata
    Lp().player.current_track.duration * 1000000)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

It seems it's already fixed on next releases.
I just noted here in case it's not fixed in next releases.
I will test again if it still present on next release.

**Comment by gnumdk** [comment]
Sure it's fixed.

**Comment by M5oul** [comment]
Ok, thanks.
