### ISSUE TITLE
"Mix songs" crashes Lollypop at startup

### ISSUE THREAD

**Issue by Blazefrost** [gnumdk/lollypop#756]
-Lollypop version: 0.9.203
-Gtk Version: 3.20.9
-Linux distribution: Arch Linux w/ kernel 4.7.4-1-ARCH

-Describe your bug here:
 After enabling "Mix songs" and trying to restart Lollypop, the window won't show up until the option was disabled using `dconf write /org/gnome/Lollypop/mix false`.

Terminal output:

```
No module named 'pylast'
    - Scrobbler disabled
    - Auto cover download disabled
    - Artist informations disabled
$ sudo pip3 install pylast
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Player::restore_state() [Errno 2] Datei oder Verzeichnis nicht gefunden: '/home/marcell/.local/share/lollypop/track_id.bin'
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 59, in on_method_call
    result = getattr(self, method_name)(*args)
  File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 278, in GetAll
    ret[property_name] = self.Get(interface, property_name)
  File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 246, in Get
    return GLib.Variant('x', Lp().player.position / 60)
  File "/usr/lib/python3.5/site-packages/lollypop/player_bin.py", line 196, in position
    if self._crossfading and self.current_track.duration > 0:
TypeError: unorderable types: NoneType() > int()
```

Used configuration that didn't work (cs-api-key omitted):
```
 ✘  ~  dconf dump /org/gnome/Lollypop/
[/]
window-maximized=false
db-version=14
cs-api-key='[omitted]'
window-position=[19, 13]
mix=true
dark-ui=true
window-size=[768, 600]
artist-artwork=true
paned-listview-width=200
background-mode=true
paned-mainlist-width=288
music-path=['/home/marcell/Musik']
save-state=true
show-compilations=false
mix-duration=3
show-genres=false
```

**Comment by gnumdk** [comment]
Already fixed in last version.
