### ISSUE TITLE
Crash on radio stream playback

### ISSUE THREAD

**Issue by mvolf** [gnumdk/lollypop#759]
-Lollypop version: 0.9.203
-Gtk Version: 3.20.9
-Linux distribution: Arch

-Describe your bug here:
Lollypop Crashes when trying to play radio stream. This issue was not present with previous versions.
Traceback after crash:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 385, in __on_current_changed
    self.__update_metadata()
  File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 343, in __update_metadata
    Lp().player.current_track.duration * 1000000)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

```

**Comment by gnumdk** [comment]
Already fixed, archlinux package is not up to date...
