### ISSUE TITLE
Lollypop crashes when attempting to play webradios

### ISSUE THREAD

**Issue by sdever** [gnumdk/lollypop#760]
-Lollypop version:
0.9.203
-Gtk Version:
3.20.9
-Linux distribution:
ArchLinux
-Describe your bug here:
Hello,

When trying to play a web radio, Lollypop crashes with the following stacktrace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 385, in __on_current_changed
    self.__update_metadata()
  File "/usr/lib/python3.5/site-packages/lollypop/mpris.py", line 343, in __update_metadata
    Lp().player.current_track.duration * 1000000)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'
```

**Comment by d9h02f** [comment]
https://github.com/gnumdk/lollypop/issues/759

**Comment by gnumdk** [comment]
Nobody looks to closed issues before posting? :-(
