### ISSUE TITLE
Lollypop closes randomly after opening

### ISSUE THREAD

**Issue by gatlinnewhouse** [gnumdk/lollypop#774]
-Music library: 91.7 GB

-Lollypop version: 0.9.209-1ppa1ubuntu1.1

-Gtk Version:

```bash
gatnewhou@laptop ~$ dpkg -l libgtk* | grep -e '^i' | grep -e 'libgtk-*[0-9]'
ii  libgtk-3-0:amd64             3.22.0-1     amd64        GTK+ graphical user interface library
ii  libgtk-3-bin                 3.22.0-1     amd64        programs for the GTK+ graphical user interface library
ii  libgtk-3-common              3.22.0-1     all          common files for the GTK+ graphical user interface library
ii  libgtk-3-dev:amd64           3.22.0-1     amd64        development files for the GTK+ library
ii  libgtk2.0-0:amd64            2.24.31-1    amd64        GTK+ graphical user interface library
ii  libgtk2.0-bin                2.24.31-1    amd64        programs for the GTK+ graphical user interface library
ii  libgtk2.0-common             2.24.31-1    all          common files for the GTK+ graphical user interface library
```
-Linux distribution: Debian Testing

-Describe your bug here: Will randomly exit out of the program after loading.

```bash
gatnewhou@laptop ~$ lollypop --enable-debugging
No module named 'wikipedia'
Advanced artist informations disabled
$ sudo pip3 install wikipedia

(lollypop:5651): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(lollypop:5651): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(lollypop:5651): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned

(lollypop:5651): libnotify-WARNING **: Failed to connect to proxy
Unknown option --enable-debugging
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
Lastfm::__on_password_lookup(): g-dbus-error-quark: The name org.freedesktop.secrets was not provided by any .service files (2)

(lollypop:5651): Gtk-WARNING **: Allocating size to lollypop+window+Window 0x2d442b0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(lollypop:5651): Gtk-WARNING **: lollypop+selectionlist+SelectionPopover 0x25588b0 is drawn without a current allocation. This should not happen.

(lollypop:5651): Gtk-WARNING **: GtkLabel 0x25536a0 is drawn without a current allocation. This should not happen.

(lollypop:5651): Gtk-WARNING **: GtkGrid 0x33a8cc0 is drawn without a current allocation. This should not happen.

(lollypop:5651): Gtk-WARNING **: GtkGrid 0x33a8b50 is drawn without a current allocation. This should not happen.

(lollypop:5651): Gtk-WARNING **: GtkGrid 0x3334cc0 is drawn without a current allocation. This should not happen.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/widgets_track.py", line 223, in __on_leave_notify
    Lp().player.preview.set_state(Gst.State.NULL)
  File "/usr/lib/python3/dist-packages/lollypop/player_bin.py", line 73, in preview
    self.set_preview_output()
  File "/usr/lib/python3/dist-packages/lollypop/player_bin.py", line 83, in set_preview_output
    pulse.set_property('device', output)
AttributeError: 'NoneType' object has no attribute 'set_property'
```

**Comment by gnumdk** [comment]
No pulseaudio? 
Fast fix: Disable preview in settings

**Comment by gnumdk** [comment]
Post a reply here on 0.9.210 release and tell me if preview work with alsa

**Comment by gnumdk** [comment]
@gatlinnewhouse 0.9.210 is out

**Comment by gatlinnewhouse** [comment]
I'm getting another issue now, see #776
