### ISSUE TITLE
Crash in preferences -> music tab

### ISSUE THREAD

**Issue by Kirek** [gnumdk/lollypop#82]
Go to preferences, music tab, add a new item, but don't select any directory. Close preferences and it crashes.

Console output:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/lollypop/settings.py", line 206, in _edit_settings_close
    path = chooser.get_dir()
  File "/usr/lib/python3.4/site-packages/lollypop/settings.py", line 282, in get_dir
    path = GLib.uri_unescape_string(self._chooser_btn.get_uri(), None)
TypeError: Argument 0 does not allow None as a value

Also it looks bad (adwaita theme)
![lollypop](https://cloud.githubusercontent.com/assets/3207574/7191400/78cfdbba-e48d-11e4-80b4-88bc3c239e44.png)

**Comment by Kirek** [comment]
Tried with another desktop and the dropdown menu looks fine, I suppose its a plasma5 issue...
