### ISSUE TITLE
App crash when clicking on artist image

### ISSUE THREAD

**Issue by gcolson** [gnumdk/lollypop#831]
-Lollypop version: 0.9.217
-Gtk Version: 3.18.9-1ubuntu3 or 2.24.30-1ubuntu
-Linux distribution: Ubuntu Studio 16.04

-Describe your bug here:
The app crash with this log whenever I click on an artist's image (to modify it) : 
```Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/lollypop/view_artist.py", line 153, in _on_image_button_release
    pop = ArtworkPopover(self._artist_ids[0])
  File "/usr/lib/python3/dist-packages/lollypop/pop_artwork.py", line 88, in __init__
    self._widget = ArtworkSearch(artist_id, None)
  File "/usr/lib/python3/dist-packages/lollypop/art_widgets.py", line 39, in __init__
    is_compilation = album.artist_ids and\
AttributeError: 'NoneType' object has no attribute 'artist_ids'```

**Comment by gcolson** [comment]
Still crashing with version 0.9.219

**Comment by gcolson** [comment]
thanks that was quick !
