### ISSUE TITLE
'NoneType' object has no attribute 'props'

### ISSUE THREAD

**Issue by thehowl** [gnumdk/lollypop#853]
- Lollypop version: 0.9.223 (according to `pacman -Qs`)
- Gtk Version: 3.22.4
- Linux distribution: Arch Linux

lollypop was running fine, with the Gstreamer plugin not found notification whatever. I tried installing the plugins, then when I launched lollypop I got this

```
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.5/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()

(lollypop:5337): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned

(lollypop:5337): Gtk-WARNING **: Failed to get the Xfce session proxy: The name org.xfce.SessionManager is not owned

(lollypop:5337): Gtk-WARNING **: Failed to get an inhibit portal proxy: The name org.freedesktop.portal.Desktop is not owned
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/lollypop/application.py", line 181, in do_startup
    self.init()
  File "/usr/lib/python3.5/site-packages/lollypop/application.py", line 136, in init
    self.player = Player()
  File "/usr/lib/python3.5/site-packages/lollypop/player.py", line 39, in __init__
    BinPlayer.__init__(self)
  File "/usr/lib/python3.5/site-packages/lollypop/player_bin.py", line 44, in __init__
    self._plugins = self._plugins1 = PluginsPlayer(self.__playbin1)
  File "/usr/lib/python3.5/site-packages/lollypop/player_plugins.py", line 39, in __init__
    self.volume.props.volume = 0.0
AttributeError: 'NoneType' object has no attribute 'props'
```

**Comment by thehowl** [comment]
After struggling to find a solutions after hours of reading logs from GST_DEBUG=4, I managed to fix it by deleting `~/.cache/gstreamer-1.0`.
