### ISSUE TITLE
GioNotify.py : GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method 'GetCapabilities'

### ISSUE THREAD

**Issue by BobbyBabes** [gnumdk/lollypop#971]
• Lollypop version: 0.9.229 [Arch Linux package](https://www.archlinux.org/packages/community/any/lollypop/)
• Gtk Version: 3.22.8 [Arch Linux package](https://www.archlinux.org/packages/extra/x86_64/gtk3/)
• Linux distribution: Linux LadyLuck 4.9.8-1-ARCH #1 SMP PREEMPT Mon Feb 6 12:59:40 CET 2017 x86_64 GNU/Linux

**Bug description :**

Starting Lollypop results in an immediate self-termination (or crash, can't tell).

Sometimes the Lollypop window is very faintly flashed for a few nanoseconds.
After the self-termination, there is a package `lollypop-portal` running under `python3` (see below).
But nothing happens and the Lollypop icon was not added to the dock. I have to `kill {pid}` the `lollypop-portal` package.

**After starting Lollypop through its desktop icon, and after it crashed :**

```
[BobbyBabes@LadyLuck ~]# ps aux | grep -ie lollypop
BobbyBabes    3999  0.0  0.2 305612 20504 ?        Sl   16:08   0:00 python3 /usr/share/lollypop-portal/lollypop-portal
BobbyBabes    4575  0.0  0.0  10768  2176 pts/2    S+   16:35   0:00 grep -ie lollypop
[BobbyBabes@LadyLuck ~]# kill 3999
```

**Starting Lollypop from the command line instead:**

```
[BobbyBabes@LadyLuck ~]# lollypop
/usr/lib/python3.6/site-packages/lollypop/lio.py:13: PyGIWarning: Soup was imported without specifying a version first. Use gi.require_version('Soup', '2.4') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, GObject, Soup
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lollypop/GioNotify.py", line 57, in on_GetCapabilities_finish
    caps = self.call_finish(result).unpack()[0]
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method 'GetCapabilities' in interface 'org.freedesktop.Notifications' at object path '/org/freedesktop/Notifications' (signature '') (19)
[BobbyBabes@LadyLuck ~]#
```

**Starting Lollypop with the `--debug` option :**

```
[BobbyBabes@LadyLuck ~]# lollypop --debug
/usr/lib/python3.6/site-packages/lollypop/lio.py:13: PyGIWarning: Soup was imported without specifying a version first. Use gi.require_version('Soup', '2.4') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, GObject, Soup
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/lollypop/GioNotify.py", line 57, in on_GetCapabilities_finish
    caps = self.call_finish(result).unpack()[0]
GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method 'GetCapabilities' in interface 'org.freedesktop.Notifications' at object path '/org/freedesktop/Notifications' (signature '') (19)
[BobbyBabes@LadyLuck ~]# 
```

**No command option to display Lollypop's version number.
Used that of the Arch linux package instead at the top of this issue. :**

```
[BobbyBabes@LadyLuck ~]# lollypop --help
/usr/lib/python3.6/site-packages/lollypop/lio.py:13: PyGIWarning: Soup was imported without specifying a version first. Use gi.require_version('Soup', '2.4') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, GObject, Soup
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_array_append_vals: assertion 'array' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_lookup: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
/usr/lib/python3.6/site-packages/gi/module.py:178: Warning: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed
  g_type = info.get_g_type()
Usage:
  lollypop [OPTION...]

Help Options:
  -h, --help                 Show help options
  --help-all                 Show all help options
  --help-gapplication        Show GApplication options
  --help-gtk                 Show GTK+ Options

Application Options:
  -a, --play-ids             Play ids
  -d, --debug                Debug lollypop
  -r, --set-rating           Rate the current track
  -t, --play-pause           Toggle playback
  -n, --next                 Go to next track
  -p, --prev                 Go to prev track
  -e, --emulate-phone        Emulate an Android Phone
  --display=DISPLAY          X display to use

[BobbyBabes@LadyLuck ~]#
```

**Comment by gnumdk** [comment]
What is your broken desktop environment?

**Comment by BobbyBabes** [comment]
Deepin 15.4

**Comment by gnumdk** [comment]
Deeping is missing org.freedesktop.Notifications.GetCapabilities() https://developer.gnome.org/notification-spec/#protocol
Report upstream...
As a workaround, you can disable notifications in dconf-editor /org/gnome/Lollypop/disable-notifications

**Comment by BobbyBabes** [comment]
Out of curiosity, what functionality am I forfeiting by disabling notifications ?

I will report upstream.  Thanks for expanding on this.

**Comment by gnumdk** [comment]
You are missing desktop notifications.

**Comment by BobbyBabes** [comment]
Oh my! :)
Thanks.

**Comment by miles28** [comment]
Same problem with Archlinux/Opnebox.
So the solution is?
`dconf write /org/gnome/Lollypop/disable-notifications true`

**Comment by BobbyBabes** [comment]
@miles28 Yes.

**Comment by JasonLG1979** [comment]
@gnumdk GioNotify can be initialized synchronously in a try except block and notifications can be made a plugin so it can more gracefully fail.
