### ISSUE TITLE
i cant run after installing

### ISSUE THREAD

**Issue by YuSuu** [gnumdk/lollypop#972]
TRANSLATORS:
https://www.transifex.com/gnumdk/lollypop
KNOWN BUGS:
• Slow scrolling: https://bugzilla.gnome.org/show_bug.cgi?id=767713
• Popover placement: https://bugzilla.gnome.org/show_bug.cgi?id=774148
WONTFIX:
• Showing bitrate

BUG MAY BE REJECTED IF MISSING:
• Lollypop version:0.9.229-1
• Gtk Version:
• Linux distribution:Linux Ted-E3 4.4.39-1-MANJARO #1 SMP PREEMPT Thu Dec 15 21:29:27 UTC 2016 x86_64 GNU/Linux

<Describe your bug here>
➜  ~ lollypop
/usr/lib/python3.6/site-packages/lollypop/lio.py:13: PyGIWarning: Soup was imported without specifying a version first. Use gi.require_version('Soup', '2.4') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, GObject, Soup
Traceback (most recent call last):
  File "/usr/bin/lollypop", line 22, in <module>
    from lollypop.application import Application
  File "/usr/lib/python3.6/site-packages/lollypop/application.py", line 39, in <module>
    from lollypop.window import Window
  File "/usr/lib/python3.6/site-packages/lollypop/window.py", line 13, in <module>
    from gi.repository import Gtk, Gio, Gdk, GLib, Gst
  File "/usr/lib/python3.5/site-packages/gi/importer.py", line 146, in load_module
    dynamic_module = load_overrides(introspection_module)
  File "/usr/lib/python3.5/site-packages/gi/overrides/__init__.py", line 125, in load_overrides
    override_mod = importlib.import_module(override_package_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.6/site-packages/gi/overrides/Gst.py", line 328, in <module>
    from . import _gi_gst
ImportError: cannot import name '_gi_gst'
➜  ~ 

first install.but i cant run ! who can help me !
i love the UI of lollypop!really!and i love its name on first glance.
:D

**Comment by gnumdk** [comment]
Your Python Gstreamer installation is broken, ask your distribution forum
